version: "3.8"

services:
  snitchvis:
    build: .
    environment:
      START_DOCKER: false
    # stdin_open: true
    # tty: true
    # init: true
    volumes:
      # make sure these files exist before running docker-compose
      - ./config.py:/app/config.py:ro
      - ./snitchvis.db:/app/snitchvis.db
      # xserver
      # - /tmp/.X11-unix:/tmp/.X11-unix
